export enum PRODUCT_CATEGORY {
  MEDICAMENTOS,
  VITAMINAS,
  SUPLEMENTOS,
  HIGIENE,
  COSMETICOS
}

export const PRODUCT_CATEGORY_LABEL = new Map<number, string>([
  [PRODUCT_CATEGORY.MEDICAMENTOS, 'Medicamentos'],
  [PRODUCT_CATEGORY.VITAMINAS, 'Vitaminas'],
  [PRODUCT_CATEGORY.SUPLEMENTOS, 'Suplementos'],
  [PRODUCT_CATEGORY.HIGIENE, 'Higiene'],
  [PRODUCT_CATEGORY.COSMETICOS, 'Cosméticos']
])
