export enum TRANSACTION_TYPE_DESCRIPTION {
  BUY,
  SELL,
  CUSTOMER_CHARGEBACK,
  DISTRIBUTOR_CHARGEBACK,
  DISCARD,
  CREDIT_ADJUST,
  DEBIT_ADJUST
}

export const TRANSACTION_TYPE_DESCRIPTION_LABEL = new Map<number, string>([
  [TRANSACTION_TYPE_DESCRIPTION.BUY, 'Compra'],
  [TRANSACTION_TYPE_DESCRIPTION.SELL, 'Venda'],
  [TRANSACTION_TYPE_DESCRIPTION.CUSTOMER_CHARGEBACK, 'Extorno de cliente'],
  [TRANSACTION_TYPE_DESCRIPTION.DISTRIBUTOR_CHARGEBACK, 'Extorno para distribuidora'],
  [TRANSACTION_TYPE_DESCRIPTION.DISCARD, 'Descarte'],
  [TRANSACTION_TYPE_DESCRIPTION.CREDIT_ADJUST, 'Ajuste de crédito'],
  [TRANSACTION_TYPE_DESCRIPTION.DEBIT_ADJUST, 'Ajuste de débito']
])
