export enum TRANSACTION_TYPE {
  COMMERCIAL,
  INTERNAL_TRANSFER,
  EXTERNAL_TRANSFER
}

export const TRANSACTION_TYPE_LABEL = new Map<number, string>([
  [TRANSACTION_TYPE.COMMERCIAL, 'Comercial'],
  [TRANSACTION_TYPE.INTERNAL_TRANSFER, 'Transferência interna'],
  [TRANSACTION_TYPE.EXTERNAL_TRANSFER, 'Transferência externa']
])
